Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -17,15 +17,6 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v3
-          
-    - name: Replace secrets in config
-      run: |
-        echo "Checking file existence..."
-        ls -la alertmanager.yml || echo "File not found!"
-        echo "Replacing token..."
-        sed -i "s#\$TELEGRAM_BOT_TOKEN#${{ secrets.TELEGRAM_BOT_TOKEN }}#g" alertmanager.yml
-        echo "Verifying replacement..."
-        grep "bot_token" alertmanager.yml || echo "Replacement failed!"
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
@@ -61,6 +52,13 @@ jobs:
         script: |
           cd ~/test-devops-task
           git pull origin master
+          sleep 3
+          echo "Checking file existence..."
+          ls -la alertmanager.yml || echo "File not found!"
+          echo "Replacing token..."
+          sed -i "s#\$TELEGRAM_BOT_TOKEN#${{ secrets.TELEGRAM_BOT_TOKEN }}#g" alertmanager.yml
+          echo "Verifying replacement..."
+          grep "bot_token" alertmanager.yml || echo "Replacement failed!"
           sleep 3
           echo "Остановка текущих контейнеров..."
           sudo docker compose down
